// Run after adding portfolio images: npm install --prefix .codex-work/performance-tools sharp
// Then: node scripts/optimize-media.cjs
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const sharp = require('../.codex-work/performance-tools/node_modules/sharp');
const root = path.resolve(__dirname, '..');
process.chdir(root);
const sources = fs.readdirSync('.').filter(name => /\.(html|js|css)$/.test(name) && !name.startsWith('media-'));
const code = sources.map(name => fs.readFileSync(name, 'utf8')).join('\n');
const walk = dir => fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
  const file = `${dir}/${entry.name}`;
  return entry.isDirectory() ? (entry.name === 'optimized' ? [] : walk(file)) : [file];
});
const dynamic = /^(assets\/pulio\/(da|jp)\/|assets\/(data-center|hyundai|pleats-mama)\/scroll\/)/;
const files = [...walk('assets'), ...walk('images')].filter(file => /\.(png|jpe?g)$/i.test(file) && (code.includes(file) || dynamic.test(file)));
const map = {};
const report = [];
fs.mkdirSync('assets/optimized', { recursive: true });
sharp.concurrency(2);

(async () => {
  for (const file of files) {
    const input = fs.readFileSync(file);
    const metadata = await sharp(input).metadata();
    const maxWidth = file.includes('/scroll/') ? 1080 : 2880;
    const width = Math.min(metadata.width, maxWidth);
    const lossless = metadata.width <= 1200;
    const key = crypto.createHash('sha256').update(input).update(`${width}:${lossless}:92`).digest('hex').slice(0, 20);
    const output = `assets/optimized/${key}.webp`;
    if (!fs.existsSync(output)) {
      await sharp(input).rotate().resize({ width, withoutEnlargement: true })
        .webp({ quality: 92, lossless, effort: 4 }).toFile(output);
    }
    const bytes = fs.statSync(output).size;
    const smaller = bytes < input.length;
    const result = smaller ? await sharp(output).metadata() : metadata;
    map[file] = { src: smaller ? output : file, width: result.width, height: result.height };
    report.push({ source: file, output: map[file].src, before: input.length, after: smaller ? bytes : input.length, width: result.width, height: result.height, lossless });
  }
  fs.writeFileSync('media-assets.js', `// Generated by scripts/optimize-media.cjs. Original images are retained.\nwindow.PortfolioMediaAssets=${JSON.stringify(map)};\n`);
  // Keep static image candidates in sync when a source image is replaced.
  for (const page of sources.filter(name => name.endsWith('.html'))) {
    const html = fs.readFileSync(page, 'utf8').replace(/<img\b[^>]*>/g, tag => {
      const original = tag.match(/\bsrc="([^"]+)"/)?.[1];
      const asset = map[original];
      if (!asset) return tag;
      tag = tag.replace(/\s(?:srcset|width|height)="[^"]*"/g, '');
      const candidate = asset.src === original ? '' : ` srcset="${asset.src}"`;
      return tag.replace(/>$/, `${candidate} width="${asset.width}" height="${asset.height}">`);
    });
    fs.writeFileSync(page, html);
  }
  fs.mkdirSync('.codex-work/performance', { recursive: true });
  fs.writeFileSync('.codex-work/performance/image-report.json', JSON.stringify(report, null, 2));
  const before = report.reduce((sum, item) => sum + item.before, 0);
  const after = report.reduce((sum, item) => sum + item.after, 0);
  console.log(JSON.stringify({ images: report.length, before, after, savedPercent: ((1 - after / before) * 100).toFixed(1) }));
})().catch(error => { console.error(error); process.exitCode = 1; });
